server:
  port: 7575

spring:
  application:
    name: BOOKSTORE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://spring-db.cn6isigu6rre.ap-south-1.rds.amazonaws.com
    username: admin
    password: 456admin
 
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true  
